Generator.MKT.QR.BackOffice/Controllers/GeneratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Generator.MKT.QR.BackOffice.Controllers
{
    public class GeneratorController : Controller
    {
        // GET: Generator
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Single()
        {
            return View();
        }

        public ActionResult Batch()
        {
            return View();
        }
    }
}

Generator.MKT.QR.BackOffice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Generator.MKT.QR.BackOffice.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Generator.MKT.QR.BackOffice/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Generator.MKT.QR.BackOffice.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChangePass()
        {
            return View();
        }
    }
}

Generator.MKT.QR.BackOffice/Views/Generator/Index.cshtml
@{
    ViewBag.Title = "Principal";
}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="~/Content/plugins/dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__wobble" src="~/Content/plugins/dist/img/bcp-login-icon.png" alt="AdminLTELogo" height="60" width="60">
        </div>
        <nav class="main-header navbar navbar-expand navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                        <i class="fas fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>

        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="#" class="brand-link">
                <img src="~/Content/plugins/dist/img/bcp-login-icon.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Generador QR</span>
            </a>
            <div class="sidebar">
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Generar QR
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Single", "Generator")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>QR por Cliente</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Batch", "Generator")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>QR por Lote</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("GetFile", "Generator")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>DESCARGAR PLANTILLA</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-header">REPORTES</li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-search"></i>
                                <p>
                                    Generar Reporte
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Single", "Report")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Unitarios</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Batch", "Report")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Lotes</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-header">USUARIOS/ROLES</li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i>
                                <p>
                                    Autorizar Personal
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "User")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Usuarios</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Permission", "User")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Roles/Permisos</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>

        <aside class="control-sidebar control-sidebar-dark"></aside>
        <footer class="main-footer">
            <strong>Copyright &copy; 2022 <a href="https://www.bcp.com.bo">Banco de Crédito de Bolivia S.A</a></strong>
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0.0
            </div>
        </footer>
    </div>

    <script src="~/Scripts/plugins/jquery/jquery.min.js"></script>
    <script src="~/Scripts/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="~/Scripts/dist/js/adminlte.js"></script>
    <script src="~/Scripts/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
    <script src="~/Scripts/plugins/raphael/raphael.min.js"></script>
    <script src="~/Scripts/plugins/jquery-mapael/jquery.mapael.min.js"></script>
    <script src="~/Scripts/plugins/jquery-mapael/maps/usa_states.min.js"></script>
    <script src="~/Scripts/plugins/chart.js/Chart.min.js"></script>
    <script src="~/Scripts/dist/js/demo.js"></script>
    <script src="~/Scripts/dist/js/pages/dashboard2.js"></script>
</body>
</html>

Generator.MKT.QR.BackOffice/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Generator.MKT.QR.BackOffice/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Generator.MKT.QR.BackOffice/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Generator.MKT.QR.BackOffice/Views/Login/ChangePass.cshtml
@{
    ViewBag.Title = "Cambio de Password";
}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/plugins/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>Generador</b>MKT</a>
        </div>
        <div class="card">
            <div class="card-body login-card-body" style="height: 350px">
                <p class="login-box-msg">Para actualizar sus credenciales debe ingresar su password actual, seguido del nuevo.</p>

                <form method="post">
                    <div class="input-group mb-5">
                        <input type="text" class="form-control" placeholder="Usuario (Matrícula)" id="userChangePass">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-5">
                        <input type="password" class="form-control" placeholder="Password Actual" id="oldPassChange">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-5">
                        <input type="password" class="form-control" placeholder="Password Nuevo" id="newPassChange">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" id="btnChangePass" class="btn btn-primary btn-block">Modificar</button>
                        </div>
                    </div>
                </form>
                <p class="mt-5 mb-1">
                    <a href="@Url.Action("Index", "Login")">Volver a Login</a>
                </p>
            </div>
        </div>
    </div>
    <script src="~/Scripts/plugins/jquery/jquery.min.js"></script>
    <script src="~/Scripts/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/dist/js/adminlte.min.js"></script>
</body>
</html>

Generator.MKT.QR.BackOffice/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/plugins/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>Generador</b>MKT</a>
        </div>
        <div class="card">
            <div class="card-body login-card-body" style="height: 300px">
                <p class="login-box-msg">Ingrese sus datos para iniciar sesión</p>

                <form action="" method="post">
                    <div class="input-group mb-5">
                        <input type="text" class="form-control" placeholder="Usuario" id="userLogin">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-5">
                        <input type="password" class="form-control" placeholder="Password" id="passwordLogin">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <button type="submit" id="btnLogin" class="btn btn-primary btn-block" href="@Url.Action("Single", "Generator")">Ingresar</button>
                        </div>
                    </div>
                </form>
                <br/>
                <p class="mb-5">
                    <a href="@Url.Action("ChangePass", "Login")">Cambiar/Actualizar Password?</a>
                </p>
            </div>
        </div>
    </div>
    <script src="~/Scripts/plugins/jquery/jquery.min.js"></script>
    <script src="~/Scripts/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/dist/js/adminlte.min.js"></script>
</body>
</html>

Generator.MKT.QR.BackOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>